"""Add external_session_id to sessions, persona to users, type/config to channels, user_channels table, remove preferred_channel_id from users, drop agent_id and context_id from sessions

Revision ID: 939b3c9aeeda
Revises: 9b1031dfcb65
Create Date: 2025-05-02 04:58:13.231143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy.dialects.postgresql as pg


# revision identifiers, used by Alembic.
revision: str = '939b3c9aeeda'
down_revision: Union[str, None] = '9b1031dfcb65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('external_session_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('persona', sa.String(length=100), nullable=True))
    op.add_column('channels', sa.Column('type', sa.String(length=50), nullable=False, server_default='web'))
    op.add_column('channels', sa.Column('config', pg.JSONB(), nullable=True))
    op.drop_constraint('users_preferred_channel_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'preferred_channel_id')
    op.create_table(
        'user_channels',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('user_id', sa.Integer, sa.ForeignKey('users.id')),
        sa.Column('channel_id', sa.Integer, sa.ForeignKey('channels.id')),
        sa.Column('contact_details', pg.JSONB(), nullable=False),
        sa.Column('is_preferred', sa.Boolean, default=False)
    )
    # Drop agent_id and context_id from sessions
    with op.batch_alter_table('sessions') as batch_op:
        batch_op.drop_column('agent_id')
        batch_op.drop_column('context_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions') as batch_op:
        batch_op.add_column(sa.Column('agent_id', sa.Integer))
        batch_op.add_column(sa.Column('context_id', sa.Integer))
    op.drop_table('user_channels')
    op.add_column('users', sa.Column('preferred_channel_id', sa.Integer, sa.ForeignKey('channels.id')))
    op.drop_column('channels', 'type')
    op.drop_column('channels', 'config')
    op.drop_column('users', 'persona')
    op.drop_column('sessions', 'external_session_id')
    # ### end Alembic commands ###
